"""Change trades_spec integer columns to biginteger

Revision ID: 46d1fb0fb953
Revises: e1a2b3c4d5e6
Create Date: 2025-08-05 10:52:03.838140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "46d1fb0fb953"
down_revision: Union[str, None] = "e1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed statements table operations as it's already been dropped
    op.alter_column(
        "trades_spec", "sales_proprietary", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec",
        "purchases_proprietary",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec", "balance_proprietary", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_individual",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_individual",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_individual",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_corporate",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_corporate",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_corporate",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_investment_trust",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_investment_trust",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_investment_trust",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_foreign",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_foreign",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_foreign",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_other_corporate",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_other_corporate",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_other_corporate",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_other",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_other",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_other",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec", "sales_total", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec", "purchases_total", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec", "balance_total", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trades_spec", "balance_total", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec", "purchases_total", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec", "sales_total", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_other",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_other",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_other",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_other_corporate",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_other_corporate",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_other_corporate",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_foreign",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_foreign",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_foreign",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_investment_trust",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_investment_trust",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_investment_trust",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_corporate",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_corporate",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_corporate",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "balance_consignment_individual",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "purchases_consignment_individual",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec",
        "sales_consignment_individual",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec", "balance_proprietary", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    op.alter_column(
        "trades_spec",
        "purchases_proprietary",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "trades_spec", "sales_proprietary", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=True
    )
    # Removed statements table recreation as it's no longer part of the schema
    # ### end Alembic commands ###
