"""add_announcements_table

Revision ID: 7e6aec3a2399
Revises: a6c57c53eda3
Create Date: 2025-08-06 15:40:48.303716

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e6aec3a2399"
down_revision: Union[str, None] = "a6c57c53eda3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("date", sa.Date(), nullable=False, comment="発表日"),
        sa.Column("code", sa.String(length=4), nullable=False, comment="銘柄コード"),
        sa.Column("fiscal_quarter", sa.String(length=50), nullable=False, comment="四半期区分"),
        sa.Column("company_name", sa.String(length=255), nullable=False, comment="会社名"),
        sa.Column("fiscal_year", sa.String(length=10), nullable=False, comment="決算期"),
        sa.Column("sector_name", sa.String(length=100), nullable=False, comment="業種名"),
        sa.Column("section", sa.String(length=50), nullable=False, comment="市場区分"),
        sa.PrimaryKeyConstraint("date", "code", "fiscal_quarter"),
        sa.UniqueConstraint("date", "code", "fiscal_quarter", name="uq_announcement"),
    )
    op.create_index(op.f("ix_announcements_code"), "announcements", ["code"], unique=False)
    op.create_index(op.f("ix_announcements_date"), "announcements", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_announcements_date"), table_name="announcements")
    op.drop_index(op.f("ix_announcements_code"), table_name="announcements")
    op.drop_table("announcements")
    # ### end Alembic commands ###
