"""Rename listed_info table to jquants_listed_info

Revision ID: a3aa5ea18e77
Revises: 0bd55ee18e0a
Create Date: 2025-08-12 10:39:57.181827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a3aa5ea18e77"
down_revision: Union[str, None] = "0bd55ee18e0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename table
    op.rename_table("listed_info", "jquants_listed_info")
    
    # Rename indexes
    op.execute("ALTER INDEX idx_listed_info_code RENAME TO idx_jquants_listed_info_code")
    op.execute("ALTER INDEX idx_listed_info_date RENAME TO idx_jquants_listed_info_date")
    
    # Rename primary key constraint
    op.execute("ALTER TABLE jquants_listed_info RENAME CONSTRAINT listed_info_pkey TO jquants_listed_info_pkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename primary key constraint back
    op.execute("ALTER TABLE jquants_listed_info RENAME CONSTRAINT jquants_listed_info_pkey TO listed_info_pkey")
    
    # Rename indexes back
    op.execute("ALTER INDEX idx_jquants_listed_info_code RENAME TO idx_listed_info_code")
    op.execute("ALTER INDEX idx_jquants_listed_info_date RENAME TO idx_listed_info_date")
    
    # Rename table back
    op.rename_table("jquants_listed_info", "listed_info")
    # ### end Alembic commands ###
