"""add weekly_margin_interest table

Revision ID: a6c57c53eda3
Revises: 46d1fb0fb953
Create Date: 2025-08-05 17:48:17.341332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6c57c53eda3"
down_revision: Union[str, None] = "46d1fb0fb953"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weekly_margin_interest",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("short_margin_trade_volume", sa.Float(), nullable=True),
        sa.Column("long_margin_trade_volume", sa.Float(), nullable=True),
        sa.Column("short_negotiable_margin_trade_volume", sa.Float(), nullable=True),
        sa.Column("long_negotiable_margin_trade_volume", sa.Float(), nullable=True),
        sa.Column("short_standardized_margin_trade_volume", sa.Float(), nullable=True),
        sa.Column("long_standardized_margin_trade_volume", sa.Float(), nullable=True),
        sa.Column("issue_type", sa.String(length=1), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("code", "date"),
    )
    op.create_index("idx_weekly_margin_interest_code", "weekly_margin_interest", ["code"], unique=False)
    op.create_index("idx_weekly_margin_interest_date", "weekly_margin_interest", ["date"], unique=False)
    op.create_index(
        "idx_weekly_margin_interest_date_issue_type", "weekly_margin_interest", ["date", "issue_type"], unique=False
    )
    op.create_index("idx_weekly_margin_interest_issue_type", "weekly_margin_interest", ["issue_type"], unique=False)
    op.drop_index("idx_celery_beat_schedules_category", table_name="celery_beat_schedules")
    op.drop_index("idx_celery_beat_schedules_name", table_name="celery_beat_schedules")
    op.drop_index("idx_celery_beat_schedules_tags", table_name="celery_beat_schedules", postgresql_using="gin")
    op.create_index(op.f("ix_celery_beat_schedules_category"), "celery_beat_schedules", ["category"], unique=False)
    op.create_index(op.f("ix_celery_beat_schedules_name"), "celery_beat_schedules", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_celery_beat_schedules_name"), table_name="celery_beat_schedules")
    op.drop_index(op.f("ix_celery_beat_schedules_category"), table_name="celery_beat_schedules")
    op.create_index(
        "idx_celery_beat_schedules_tags", "celery_beat_schedules", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_index("idx_celery_beat_schedules_name", "celery_beat_schedules", ["name"], unique=False)
    op.create_index("idx_celery_beat_schedules_category", "celery_beat_schedules", ["category"], unique=False)
    op.drop_index("idx_weekly_margin_interest_issue_type", table_name="weekly_margin_interest")
    op.drop_index("idx_weekly_margin_interest_date_issue_type", table_name="weekly_margin_interest")
    op.drop_index("idx_weekly_margin_interest_date", table_name="weekly_margin_interest")
    op.drop_index("idx_weekly_margin_interest_code", table_name="weekly_margin_interest")
    op.drop_table("weekly_margin_interest")
    # ### end Alembic commands ###
