"""add_company_tables

Revision ID: c2e3a9be79f7
Revises: 2a3b4b6d6788
Create Date: 2025-06-26 06:50:37.525202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2e3a9be79f7'
down_revision: Union[str, None] = '2a3b4b6d6788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='銘柄コード'),
    sa.Column('company_name', sa.String(length=200), nullable=False, comment='会社名（日本語）'),
    sa.Column('company_name_english', sa.String(length=200), nullable=True, comment='会社名（英語）'),
    sa.Column('sector17_code', sa.String(length=10), nullable=True, comment='17業種区分コード'),
    sa.Column('sector33_code', sa.String(length=10), nullable=True, comment='33業種区分コード'),
    sa.Column('scale_category', sa.String(length=50), nullable=True, comment='規模区分'),
    sa.Column('market_code', sa.String(length=10), nullable=True, comment='市場区分コード'),
    sa.Column('margin_code', sa.String(length=10), nullable=True, comment='信用区分'),
    sa.Column('reference_date', sa.Date(), nullable=False, comment='情報基準日'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='アクティブフラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_active_market', 'companies', ['is_active', 'market_code'], unique=False)
    op.create_index('ix_companies_active_sector17', 'companies', ['is_active', 'sector17_code'], unique=False)
    op.create_index(op.f('ix_companies_code'), 'companies', ['code'], unique=True)
    op.create_index('ix_companies_code_date', 'companies', ['code', 'reference_date'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_market_code'), 'companies', ['market_code'], unique=False)
    op.create_index('ix_companies_market_sector', 'companies', ['market_code', 'sector17_code'], unique=False)
    op.create_index('ix_companies_name_search', 'companies', ['company_name'], unique=False, postgresql_using='gin', postgresql_ops={'company_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_companies_sector17_code'), 'companies', ['sector17_code'], unique=False)
    op.create_index(op.f('ix_companies_sector33_code'), 'companies', ['sector33_code'], unique=False)
    op.create_table('company_sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_date', sa.Date(), nullable=False, comment='同期対象日'),
    sa.Column('sync_type', sa.String(length=20), nullable=False, comment='同期タイプ（full/incremental）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='同期状態（running/completed/failed）'),
    sa.Column('total_companies', sa.Integer(), nullable=True, comment='総企業数'),
    sa.Column('new_companies', sa.Integer(), nullable=True, comment='新規企業数'),
    sa.Column('updated_companies', sa.Integer(), nullable=True, comment='更新企業数'),
    sa.Column('deleted_companies', sa.Integer(), nullable=True, comment='削除企業数'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='開始時刻'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完了時刻'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='エラーメッセージ'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_history_date_status', 'company_sync_history', ['sync_date', 'status'], unique=False)
    op.create_index('ix_sync_history_started_at', 'company_sync_history', ['started_at'], unique=False)
    op.create_table('market_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='市場コード'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='市場名'),
    sa.Column('name_english', sa.String(length=100), nullable=True, comment='市場名（英語）'),
    sa.Column('description', sa.Text(), nullable=True, comment='市場説明'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='表示順序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='アクティブフラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_active_order', 'market_masters', ['is_active', 'display_order'], unique=False)
    op.create_index(op.f('ix_market_masters_code'), 'market_masters', ['code'], unique=True)
    op.create_table('sector17_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='17業種コード'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='業種名'),
    sa.Column('name_english', sa.String(length=100), nullable=True, comment='業種名（英語）'),
    sa.Column('description', sa.Text(), nullable=True, comment='業種説明'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='表示順序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='アクティブフラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector17_masters_code'), 'sector17_masters', ['code'], unique=True)
    op.create_table('sector33_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='33業種コード'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='業種名'),
    sa.Column('name_english', sa.String(length=100), nullable=True, comment='業種名（英語）'),
    sa.Column('description', sa.Text(), nullable=True, comment='業種説明'),
    sa.Column('sector17_code', sa.String(length=10), nullable=False, comment='対応する17業種コード'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='表示順序'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='アクティブフラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector33_masters_code'), 'sector33_masters', ['code'], unique=True)
    op.create_index(op.f('ix_sector33_masters_sector17_code'), 'sector33_masters', ['sector17_code'], unique=False)
    op.create_index('ix_sector33_sector17_order', 'sector33_masters', ['sector17_code', 'display_order'], unique=False)
    op.drop_index('ix_stocks_id', table_name='stocks')
    op.drop_index('ix_stocks_symbol', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('ix_stock_prices_id', table_name='stock_prices')
    op.drop_table('stock_prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stock_prices_pkey')
    )
    op.create_index('ix_stock_prices_id', 'stock_prices', ['id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stocks_pkey')
    )
    op.create_index('ix_stocks_symbol', 'stocks', ['symbol'], unique=False)
    op.create_index('ix_stocks_id', 'stocks', ['id'], unique=False)
    op.drop_index('ix_sector33_sector17_order', table_name='sector33_masters')
    op.drop_index(op.f('ix_sector33_masters_sector17_code'), table_name='sector33_masters')
    op.drop_index(op.f('ix_sector33_masters_code'), table_name='sector33_masters')
    op.drop_table('sector33_masters')
    op.drop_index(op.f('ix_sector17_masters_code'), table_name='sector17_masters')
    op.drop_table('sector17_masters')
    op.drop_index(op.f('ix_market_masters_code'), table_name='market_masters')
    op.drop_index('ix_market_active_order', table_name='market_masters')
    op.drop_table('market_masters')
    op.drop_index('ix_sync_history_started_at', table_name='company_sync_history')
    op.drop_index('ix_sync_history_date_status', table_name='company_sync_history')
    op.drop_table('company_sync_history')
    op.drop_index(op.f('ix_companies_sector33_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector17_code'), table_name='companies')
    op.drop_index('ix_companies_name_search', table_name='companies', postgresql_using='gin', postgresql_ops={'company_name': 'gin_trgm_ops'})
    op.drop_index('ix_companies_market_sector', table_name='companies')
    op.drop_index(op.f('ix_companies_market_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index('ix_companies_code_date', table_name='companies')
    op.drop_index(op.f('ix_companies_code'), table_name='companies')
    op.drop_index('ix_companies_active_sector17', table_name='companies')
    op.drop_index('ix_companies_active_market', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
