"""fix_announcements_code_column_length

Revision ID: da6b106853ae
Revises: 7e6aec3a2399
Create Date: 2025-08-06 16:12:12.927353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da6b106853ae"
down_revision: Union[str, None] = "7e6aec3a2399"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'code',
                    existing_type=sa.VARCHAR(length=4),
                    type_=sa.String(length=5),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'code',
                    existing_type=sa.VARCHAR(length=5),
                    type_=sa.String(length=4),
                    existing_nullable=False)
    # ### end Alembic commands ###
